version: 1
disable_existing_loggers: true
formatters:
    standard:
        format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
    custom_formatter:
        format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
handlers:
    default:
        formatter: standard
        class: logging.StreamHandler
        stream: ext://sys.stdout
    stream_handler:
        formatter: custom_formatter
        class: logging.StreamHandler
        stream: ext://sys.stdout
loggers:
    uvicorn:
        handlers: [default]
        level: TRACE
        propagate: false
    uvicorn.access:
        handlers: [stream_handler]
        level: TRACE
        propagate: false
    uvicorn.error:
        handlers: [stream_handler]
        level: TRACE
        propagate: false
    uvicorn.asgi:
        handlers: [stream_handler]
        level: TRACE
        propagate: false
