[project]
name = "discordbot-api"
version = "1.0"
description = "API to handle db calls for github.com/N-Fahey/discordbot"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiomysql>=0.3.2",
    "alembic>=1.19.1",
    "fastapi[standard]>=0.141.1",
    "sqlalchemy>=2.0.52",
    "cryptography>=50.0.0"
]
